/-
  Generated by lsc from logic.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «logic.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method sumTo (arr : Array Int) (n : Nat) return (res : Int)
  do
    return Pure.sumTo arr n

method expenseDelta (paidBy : Int) (amount : Int) (share : Int) (member : Int) return (res : Int)
  ensures paidBy = member → res = amount - share
  ensures paidBy ≠ member → res = 0 - share
  do
    return Pure.expenseDelta paidBy amount share member

method settlementDelta («from» : Int) («to» : Int) (amount : Int) (member : Int) return (res : Int)
  ensures «from» = member → res = amount
  ensures «to» = member → «from» ≠ member → res = 0 - amount
  ensures «from» ≠ member → «to» ≠ member → res = 0
  do
    return Pure.settlementDelta «from» «to» amount member

method validExpense (e : Expense) (memberCount : Nat) return (res : Bool)
  do
    return Pure.validExpense e memberCount

method allExpensesValid (expenses : Array Expense) (n : Nat) (memberCount : Nat) return (res : Bool)
  do
    return Pure.allExpensesValid expenses n memberCount

method validSettlement (s : Settlement) (memberCount : Nat) return (res : Bool)
  do
    return Pure.validSettlement s memberCount

method allSettlementsValid (settlements : Array Settlement) (n : Nat) (memberCount : Nat) return (res : Bool)
  do
    return Pure.allSettlementsValid settlements n memberCount

method inv (model : Model) return (res : Bool)
  do
    return Pure.inv model

method computeBalance (paidBy : Array Int) (amounts : Array Int) (shares : Array Int) (settFrom : Array Int) (settTo : Array Int) (settAmounts : Array Int) (member : Nat) (expenseCount : Nat) (settlementCount : Nat) return (res : Int)
  do
    let mut balance : Int := 0
    let mut i : Nat := 0
    while i < expenseCount
      invariant i ≤ expenseCount
      decreasing expenseCount - i
    do
      let _t0 ← expenseDelta paidBy[i]! amounts[i]! shares[i]! member
      balance := balance + _t0
      i := i + 1
    let mut j : Nat := 0
    while j < settlementCount
      invariant j ≤ settlementCount
      decreasing settlementCount - j
    do
      let _t1 ← settlementDelta settFrom[j]! settTo[j]! settAmounts[j]! member
      balance := balance + _t1
      j := j + 1
    return balance

method step (model : Model) (action : Action) return (res : Model)
  require Pure.inv model
  ensures Pure.inv res
  do
    return Pure.step model action
