/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import Velvet.Syntax
import Velvet.Std

structure Expense where
  paidBy : Int
  amount : Int
  shares : Array Int
deriving Repr, Inhabited, DecidableEq

structure Settlement where
  «from» : Int
  «to» : Int
  amount : Int
deriving Repr, Inhabited, DecidableEq

inductive Action where
  | addExpense (expense : Expense) : Action
  | addSettlement (settlement : Settlement) : Action
deriving Repr, Inhabited

structure Model where
  memberCount : Nat
  expenses : Array Expense
  settlements : Array Settlement
deriving Repr, Inhabited, DecidableEq

namespace Pure

def sumTo (arr : Array Int) (n : Nat) : Int :=
  if n = 0 then
    0
  else
    sumTo arr (n - 1) + arr[n - 1]!

def expenseDelta (paidBy : Int) (amount : Int) (share : Int) (member : Int) : Int :=
  if paidBy = member then
    amount - share
  else
    0 - share

def settlementDelta («from» : Int) («to» : Int) (amount : Int) (member : Int) : Int :=
  if «from» = member then
    amount
  else
    if «to» = member then
      0 - amount
    else
      0

def validExpense (e : Expense) (memberCount : Nat) : Bool :=
  e.paidBy ≥ 0 ∧ e.paidBy < memberCount ∧ e.amount ≥ 0 ∧ (e.shares).size = memberCount ∧ sumTo e.shares memberCount = e.amount

def allExpensesValid (expenses : Array Expense) (n : Nat) (memberCount : Nat) : Bool :=
  if n = 0 then
    true
  else
    validExpense expenses[n - 1]! memberCount ∧ allExpensesValid expenses (n - 1) memberCount

def validSettlement (s : Settlement) (memberCount : Nat) : Bool :=
  s.«from» ≥ 0 ∧ s.«to» ≥ 0 ∧ s.«from» < memberCount ∧ s.«to» < memberCount ∧ s.«from» ≠ s.«to» ∧ s.amount ≥ 0

def allSettlementsValid (settlements : Array Settlement) (n : Nat) (memberCount : Nat) : Bool :=
  if n = 0 then
    true
  else
    validSettlement settlements[n - 1]! memberCount ∧ allSettlementsValid settlements (n - 1) memberCount

def inv (model : Model) : Bool :=
  model.memberCount ≥ 0 ∧ allExpensesValid model.expenses (model.expenses).size model.memberCount ∧ allSettlementsValid model.settlements (model.settlements).size model.memberCount

def step (model : Model) (action : Action) : Model :=
  match action with
  | .addExpense _expense =>
    let e := _expense
    if e.paidBy < 0 then
      model
    else
      if e.paidBy ≥ model.memberCount then
        model
      else
        if e.amount < 0 then
          model
        else
          if (e.shares).size ≠ model.memberCount then
            model
          else
            if sumTo e.shares model.memberCount ≠ e.amount then
              model
            else
              { memberCount := model.memberCount, expenses := Array.push model.expenses e, settlements := model.settlements }
  | .addSettlement _settlement =>
    let s := _settlement
    if s.«from» < 0 then
      model
    else
      if s.«to» < 0 then
        model
      else
        if s.«from» ≥ model.memberCount then
          model
        else
          if s.«to» ≥ model.memberCount then
            model
          else
            if s.«from» = s.«to» then
              model
            else
              if s.amount < 0 then
                model
              else
                { memberCount := model.memberCount, expenses := model.expenses, settlements := Array.push model.settlements s }

end Pure
